### ISSUE TITLE
Errors when attempting to Set Texel Density 

### ISSUE THREAD

**Issue by j-conrad** [franMarz/TexTools-Blender#113]
Sometimes I get errors when attempting to Set the Texel Density on a given selection of faces. It's usually something like the following:

`Python: Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\TexTools_1_4_4\op_texel_density_set.py", line 49, in execute
    set_texel_density(
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\TexTools_1_4_4\op_texel_density_set.py", line 197, in set_texel_density
    utilities_uv.selection_restore()
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\TexTools_1_4_4\utilities_uv.py", line 122, in selection_restore
    bpy.ops.uv.cursor_set(contextViewUV, location=settings.selection_uv_pivot_pos)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.uv.cursor_set.poll() failed, context is incorrect

location: <unknown location>:-1

`

I can't seem to figure out what conditions cause the error(s).

Blender v. 2.93.5
Windows 10
TexTools v. 1.4.4

**Comment by franMarz** [comment]
You are not using the latest version, but the latest release. Please use the latest version, maybe I fixed that ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip))

**Comment by franMarz** [comment]
If you updated the addon and are still getting the same issue, can you please provide the file you are using with the problematic faces selected?

**Comment by franMarz** [comment]
Closing due to inactivity.
