### ISSUE TITLE
Cannot be run in Blender 3.0.

### ISSUE THREAD

**Issue by okamototomoyuki** [franMarz/TexTools-Blender#114]
When I press the Bake 1x button, I get the following error:
```
Python: Traceback (most recent call last):
  File "C:\Users\okamo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools_1_4_4\op_bake.py", line 152, in execute
    ub.store_bake_settings()
  File "C:\Users\okamo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools_1_4_4\utilities_bake.py", line 73, in store_bake_settings
    settings.use_progressive_refine = bpy.context.scene.cycles.use_progressive_refine
AttributeError: 'CyclesRenderSettings' object has no attribute 'use_progressive_refine'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\okamo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools_1_4_4\op_bake.py", line 152, in execute
    ub.store_bake_settings()
  File "C:\Users\okamo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools_1_4_4\utilities_bake.py", line 73, in store_bake_settings
    settings.use_progressive_refine = bpy.context.scene.cycles.use_progressive_refine
AttributeError: 'CyclesRenderSettings' object has no attribute 'use_progressive_refine'

location: <unknown location>:-1
```
It happens in any mode, AO, normal or otherwise.

**Comment by franMarz** [comment]
Are you using the latest version? ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip))

**Comment by naeternas** [comment]
Almost the same problem with your latest version. Blender v 3.0.0 (4 Dec). CPU device.
- - - - - - - - - 
Python: Traceback (most recent call last):
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 185, in execute
    bake(
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 441, in bake
    assign_tune_materials(obj, setup_bake_nodes=True)
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 384, in assign_tune_materials
    channel_ignore(modes['alpha'].relink['n'], slot.material)
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 855, in channel_ignore
    bsdf_node.inputs[channel].default_value = 1.0
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'

location: <unknown location>:-1

-----------------------------------

Working: AO, Diffuse, Face Selection, BevelMask, Cavity, Dust, Elem Id, Mat Id, Obj Bevel, Tang Bevel, Paint Base, Position, Thickness, Wireframe
Not working: Metallic, Roughness, BaseColor, Alpha, TangentNormal, Anisotropic, Anis Ro, Clearcoat, Clearcoat Ro, Combined, Curvature, Emission, Em Pow, Env, Gloss, Obj Normal, Shadow, Sheen, Sheen Tint, Specular, Spec Tint, SSS Color, SSS Strength, Transmission, Trans Rough, UV,

**Comment by okamototomoyuki** [comment]
> Are you using the latest version? ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip))

I'm sorry. I was testing with the Latest Version (1.4.4).
I tried the master branch and it worked fine.

**Comment by franMarz** [comment]
> Almost the same problem with your latest version. Blender v 3.0.0 (4 Dec). CPU device.
> 

Not the same problem at all. I'll look into that though.
