### ISSUE TITLE
Baking issue. Nodal material attributes type changes.

### ISSUE THREAD

**Issue by franMarz** [franMarz/TexTools-Blender#115]
Almost the same problem with your latest version. Blender v 3.0.0 (4 Dec). CPU device.
- - - - - - - - - 
Python: Traceback (most recent call last):
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 185, in execute
    bake(
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 441, in bake
    assign_tune_materials(obj, setup_bake_nodes=True)
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 384, in assign_tune_materials
    channel_ignore(modes['alpha'].relink['n'], slot.material)
  File "C:\Users\naete\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\TexTools-Blender-master\op_bake.py", line 855, in channel_ignore
    bsdf_node.inputs[channel].default_value = 1.0
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'

location: <unknown location>:-1

-----------------------------------

Working: AO, Diffuse, Face Selection, BevelMask, Cavity, Dust, Elem Id, Mat Id, Obj Bevel, Tang Bevel, Paint Base, Position, Thickness, Wireframe
Not working: Metallic, Roughness, BaseColor, Alpha, TangentNormal, Anisotropic, Anis Ro, Clearcoat, Clearcoat Ro, Combined, Curvature, Emission, Em Pow, Env, Gloss, Obj Normal, Shadow, Sheen, Sheen Tint, Specular, Spec Tint, SSS Color, SSS Strength, Transmission, Trans Rough, UV,

_Originally posted by @naeternas in https://github.com/SavMartin/TexTools-Blender/issues/114#issuecomment-986196404_

**Comment by franMarz** [comment]
Related to changes in the number of slots of the Principles BSDF material. Watch out for the bsdf_node.subsurface_method, Burley has less input sockets than Random Walk.
