### ISSUE TITLE
bpy.ops.ui.textools_popup

### ISSUE THREAD

**Issue by TitusLVR** [franMarz/TexTools-Blender#127]
Hello,
It happened for texture reload function and maybe some other functions not sure.
bpy.ops.ui.textools_popup was deleted for purpose or accidentally? If not I can restore and commit.

```Error: Python: Traceback (most recent call last):
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender\op_texture_reload_all.py", line 16, in execute
    main(context)
  File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender\op_texture_reload_all.py", line 59, in main
    bpy.ops.ui.textools_popup('INVOKE_DEFAULT', message=message)
  File "C:\Blender Foundation\daily\blender-3.1.0-alpha+master.0e86c60c28b6-windows.amd64-release\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.ui.textools_popup" error, could not be found

location: <unknown location>:-1```

**Comment by franMarz** [comment]
It was my fault, I deleted it here [here](https://github.com/SavMartin/TexTools-Blender/commit/3810fec6449839c3283292c0dafbcbd2c080309b), I think I got confused by the commented-out line inside the register function. So thank you Titus for fixing it!
