### ISSUE TITLE
Crashing on baking anything in 3.x

### ISSUE THREAD

**Issue by Vector-Impulse** [franMarz/TexTools-Blender#131]
I'm getting this error for some reason when I bake anything in 3.1
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools_1_4_4\op_bake.py", line 191, in execute
    bake(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools_1_4_4\op_bake.py", line 509, in bake
    cycles_bake(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools_1_4_4\op_bake.py", line 948, in cycles_bake
    bpy.context.scene.cycles.samples = samples
TypeError: bpy_struct: item.attr = val: CyclesRenderSettings.samples expected an int type, not float

location: <unknown location>:-1
```

**Comment by franMarz** [comment]
Are you using the latest version ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip))?

**Comment by Vector-Impulse** [comment]
Oh ok, the master copy works fine. The one version I was using initially was from the releases version. Thanks for being patient with me.

**Comment by franMarz** [comment]
No problem, come back anytime you have an issue. Have a nice day.
