### ISSUE TITLE
Rectify not working

### ISSUE THREAD

**Issue by crabo0om** [franMarz/TexTools-Blender#147]
When trying to rectify my UVs  always get this error, no matter what geometry i try it on.
Last time it worked for me was with Blender 2.8. But now with 3.1 it doesn´t work anymore :(

Python: Traceback (most recent call last):
  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 38, in execute

  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 56, in rectify

  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 64, in main
    filteredVerts, selFaces, vertsDict, discarded_faces = ListsOfVerts(bm, uv_layers, selFacesMix, faces_loops)
AttributeError: module 'time' has no attribute 'clock'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 38, in execute

  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 56, in rectify

  File "C:\Users\grafa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\TexTools-Blender-master\op_rectify.py", line 64, in main
    filteredVerts, selFaces, vertsDict, discarded_faces = ListsOfVerts(bm, uv_layers, selFacesMix, faces_loops)
AttributeError: module 'time' has no attribute 'clock'

location: <unknown location>:-1

**Comment by crabo0om** [comment]
Oh, nevermind. I just removed the plugin, restartet blender and reinstalled the plugin and now it works...

**Comment by franMarz** [comment]
Solved then
