### ISSUE TITLE
Issue: Rectifying UVs Gives Error In Current Scene

### ISSUE THREAD

**Issue by SethTooQuick** [franMarz/TexTools-Blender#157]
Python: Traceback (most recent call last):
  File "C:\Users\setha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TexTools_1_5\op_rectify.py", line 35, in execute
    utilities_uv.multi_object_loop(rectify, self, context)
  File "C:\Users\setha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TexTools_1_5\utilities_uv.py", line 66, in multi_object_loop
    func(*args, **kwargs)
  File "C:\Users\setha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TexTools_1_5\op_rectify.py", line 58, in rectify
    utilities_uv.selection_restore(bm, uv_layers)
  File "C:\Users\setha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TexTools_1_5\utilities_uv.py", line 151, in selection_restore
    bpy.ops.uv.cursor_set(contextViewUV, location=settings.selection_uv_pivot_pos)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.uv.cursor_set.poll() failed, context is incorrect

The file the error is happening in
[service_cart.zip](https://github.com/SavMartin/TexTools-Blender/files/10787580/service_cart.zip)

**Comment by franMarz** [comment]
Having the Image Editor opened at the same time that the UV Editor is causing this issue. We'll see how we can solve it.

**Comment by SethTooQuick** [comment]
Awesome! Thanks everyone for maintaining TexTools!
