### ISSUE TITLE
3.61 bug

### ISSUE THREAD

**Issue by sangouzhi** [franMarz/TexTools-Blender#169]
Python: Traceback (most recent call last):
  File "C:\Users\Y\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\TexTools_1_5\op_texel_checker_map.py", line 26, in execute
    assign_checker_map(
  File "C:\Users\Y\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\TexTools_1_5\op_texel_checker_map.py", line 120, in assign_checker_map
    apply_image(obj, image)
  File "C:\Users\Y\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\TexTools_1_5\op_texel_checker_map.py", line 216, in apply_image
    nodo2 = tree.nodes['Principled BSDF']
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**Comment by franMarz** [comment]
Have you installed the latest version of TexTools ([master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip))?

**Comment by sangouzhi** [comment]
the latest version of TexTools  is OK great thankyou

**Comment by franMarz** [comment]
Great!
