### ISSUE TITLE
Unable to bake diffuse textures

### ISSUE THREAD

**Issue by milanbt** [franMarz/TexTools-Blender#17]
To replicate:

Make 2 cubes with 2 different materials.
Select both cubes and UV unwrap.
Make new texture to save diffuse bake to.
Upon pressing bake, I get this:

````
Traceback (most recent call last):
  File "C:\Users\noname\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\TexTools-Blender-master\op_bake.py", line 73, in execute
    ray_distance = bpy.context.scene.texToolsSettings.bake_ray_distance
  File "C:\Users\noname\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\TexTools-Blender-master\op_bake.py", line 159, in bake
    image = setup_image(mode, name_texture, render_width, render_height, path, is_clear)
  File "C:\Users\noname\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\TexTools-Blender-master\op_bake.py", line 345, in setup_image
    is_float_32 = bpy.context.preferences.addons["textools"].preferences.bake_32bit_float == '32'
KeyError: 'bpy_prop_collection[key]: key "textools" not found'

location: <unknown location>:-1

```
`

**Comment by SavMartin** [comment]
Hi, uninstall textools and install this one : https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.80/textools.zip
