### ISSUE TITLE
Unable to bake anything

### ISSUE THREAD

**Issue by bruhtusmomentus** [franMarz/TexTools-Blender#20]
After trying to bake a textured helmet, I received this error:

Traceback (most recent call last):
File "/Users/myusername/Library/Aplication Support/Blender/2.82/scripts/addons/TexTools/op_bake.py", line 73, in execute
        ray_distance = bpy.context.scene.texToolsSettngs.bake_ray_distance
File "/Users/myusername/Library/Application Support/Blender/2.82/scripts/addons/TexTools/op_bake.py", line 159, in bake
        image = setup_image(mode, name_texture, render_width, render_height, path, is_clear)
File "/Users/mysusername/Library/Application Support/Blender/2.82/scripts/addons/TexTools/op_bake.py", line 345, in setup_image
        is_float_32 = bpy.context.preferences.addons["textools"].preferences.bake_32bit_float == '32'
KeyError: 'bby_prop_collection[key] "textools" not found'

location: <unknown location>:-1

Note: I'm on a mac

**Comment by SavMartin** [comment]
Fixed , you can download the rigth one here.
https://github.com/SavMartin/TexTools-Blender/releases/download/TexTools_2.8x/Textools.zip

**Comment by bruhtusmomentus** [comment]
Works, thank you!
