### ISSUE TITLE
Issue when re-enabling on 2.91

### ISSUE THREAD

**Issue by JustSaiyan01** [franMarz/TexTools-Blender#29]
When I disable the latest version of TexTools and then re-enable I got the following error:
-------------------------

Traceback (most recent call last):
  File "C:\blender-2.91.0-144f780c71ed-windows64\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\textools\__init__.py", line 1436, in register
    utilities_ui.icon_register(icon)
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\textools\utilities_ui.py", line 61, in icon_register
    preview_icons.load(name, os.path.join(icons_dir, fileName), 'IMAGE')
  File "C:\blender-2.91.0-144f780c71ed-windows64\2.91\scripts\modules\bpy\utils\previews.py", line 96, in load
    raise KeyError("key %r already exists" % name)
KeyError: "key 'bake_anti_alias' already exists"

-------------------------

I should note that what I remove the addon and re-install it the error does not pop up.

**Comment by JustSaiyan01** [comment]
Had to close Blender 2.91 down and re-install the addon for it to turn back on, couldn't just turn it on after disabling it in one session.
