### ISSUE TITLE
Addon can't be enabled in Blender 2.81

### ISSUE THREAD

**Issue by BlenderPete** [franMarz/TexTools-Blender#6]
If I try to enable the addon in the preferences the addon gives the following message:
Exception in module register(): F:\Blender\2.81Beta\2.81\scripts\addons\textools\__init__.py
Traceback (most recent call last):
  File "F:\Blender\2.81Beta\2.81\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "F:\Blender\2.81Beta\2.81\scripts\addons\textools\__init__.py", line 1436, in register
    utilities_ui.icon_register(icon)
  File "F:\Blender\2.81Beta\2.81\scripts\addons\textools\utilities_ui.py", line 61, in icon_register
    preview_icons.load(name, os.path.join(icons_dir, fileName), 'IMAGE')
  File "F:\Blender\2.81Beta\2.81\scripts\modules\bpy\utils\previews.py", line 97, in load
    raise KeyError("key {name!r} already exists")
KeyError: 'key {name!r} already exists'

**Comment by ghost** [comment]
Same happens for me on 2.80

EDIT: Restarting Blender fixed it

**Comment by ghost** [comment]
I made a pull request, small change but removes unnecessary headache
